version: '2'

volumes:
  nextcloud:
  db:

services:
  re-proxy:
    image: nginx:1.16-alpine
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./r-proxy:/etc/nginx/conf.d/:ro
    depends_on:
      - web
      - collabora
    container_name: proxy
 
  redis:
    image: redis:5-alpine  
    restart: always 
    container_name: redis

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/nextcloud
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - PGDATA=/var/lib/postgresql/nextcloud
    container_name: postgres

  app:
    image: nextcloud:17-fpm-alpine
    links:
      - db
      - redis  
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.local.com
    extra_hosts:
      - "nextcloud.local.com:192.168.1.2"
    restart: always
    container_name: nextcloud

  web:
    image: nginx:1.17-alpine
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
    container_name: nginx

  collabora:
    build: 
      context: ./collabora
      dockerfile: Dockerfile
    image: p4ng/collabora:1.0
    links:
      - app
    expose:
      - "9980"
    environment:
      - domain=nextcloud\\.local\\.com
      - username=admin
      - password=password
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
    extra_hosts:
      - "nextcloud.local.com:192.168.1.2"
    cap_add:
      - MKNOD
    restart: always
    container_name: collabora   
