version: '2'

volumes:
  nextcloud:
  db:

services:
  re-proxy:
    image: nginx:1.16-alpine
    ports:
     - "80:80"
    volumes:
     - ./r-proxy:/etc/nginx/conf.d/:ro
    depends_on:
     - web
  
  redis:
    image: redis:5-alpine  
    restart: always 

  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/nextcloud
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - PGDATA=/var/lib/postgresql/nextcloud

  app:
    image: nextcloud:17-fpm-alpine
    links:
      - db
      - redis  
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.local
    restart: always

  web:
    image: nginx:1.17-alpine
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
